name: Sync Nodes to Test Config
on:
  schedule:
    - cron: '0 0 * * 0'   # Time--> minute hour day month day-of-the-week
  workflow_dispatch:      # Allows you to click "Run" manually

permissions:
  contents: write         # Crucial: Allows the bot to save test.yaml

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Run Update
        run: python automate.py

      - name: Commit and Push
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "ConfigBot"
          git add test.yaml
          # If nothing changed, this won't error out
          git commit -m "Auto-update test.yaml" || exit 0
          git push
